version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "interviewdb"
    ports:
      - "5433:5432"